apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3  
      maxSurge: 0         
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: rajathreghunath/flask-app:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_HOST
            value: "mongo-service"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
