apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2  
      maxSurge: 2         
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: rajathreghunath/flask-app:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_HOST
            value: "mongo-service"
